spring:
  application:
    name: Scrapper-App
server:
  port: 8096
management:
  endpoints:
    web: 
      exposure:
        include: "*"
media:
  source:
    anime-flv-url: https://www3.animeflv.net/
    youtube-url: https://www.youtube.com/results
